User.create!([
  {password_digest: "$2a$12$Ef7lybzs93Q3MWv1o.LRU.oyM0R.29e5rg8gE0m2cilfopiuaeK8y", is_teacher: false, name: "Tom Reviewer", education: "", bio: "", subjects: "", zipcode: "", preferred_contact: "", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Tom@gmail.com"},
  {password_digest: "$2a$12$n7B896uDqHpeSVdU3JgqNOYfWGrFJRtDry6JSBX3ZWwtrlaRgRTNu", is_teacher: false, name: "Jeff Reviewer", education: "", bio: "", subjects: "", zipcode: "", preferred_contact: "", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Jeff@gmail.com"},
  {password_digest: "$2a$12$Bsu3Hvaz16I3I8lIJiWFJuTM4JqRDzGtvZb/W021pJfupjeNpX/f2", is_teacher: false, name: "Paul Reviewer", education: "", bio: "", subjects: "", zipcode: "", preferred_contact: "", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Paul@gmail.com"},
  {password_digest: "$2a$12$UA4evG8XatWGz/WLOvmyYexd4rVsXZXLOMdlmP4UTpBsZ/LYPjnhu", is_teacher: true, name: "Mary Teach", education: "Many years of study across the U.S.", bio: "Excellent character, person of substance", subjects: "Math, English", zipcode: "11516", preferred_contact: "phone", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Mary@gmail.com"},
  {password_digest: "$2a$12$PSPTRZ5LNn/bRpURG3o..eYIFXVePMWc3aaladcg7/ox1mzZ/HHIO", is_teacher: true, name: "Silvia Peppermill", education: "All Schools attended", bio: "Having travelled all throughout europe and asia after college, horizons are bright", subjects: "Biology,Chemistry", zipcode: "23185", preferred_contact: "phone or email", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Silvia@gmail.com"},
  {password_digest: "$2a$12$cybzSUyzgFG1OH/v7SAMQuwXsXe1oc8LVJhxl8KHi9IxUIhQKfjYO", is_teacher: true, name: "Fred Mcguffin", education: "Extremely Vastly Educated", bio: "Hail from normandy and steeped in the arts", subjects: "History, Digital Art Design", zipcode: "90028", preferred_contact: "email or phone", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Fred@gmail.com"},
  {password_digest: "$2a$12$4rx1T3gPMF7U8PUpPtvf/OEW57lC7szqkNpOHNMnkClrZtZrhCQ.y", is_teacher: true, name: "Summer Peter", education: "1998 - 2002 Columbia University Bachelors in Teaching, 2002 - 2006 Columbia University MBA", bio: "Peace core work in belize", subjects: "Geo-Politics, Finance", zipcode: "11222", preferred_contact: "email or phone please", image_url: "https://i5.walmartimages.com/asr/3fa28e82-d16a-4476-884d-5f1d13ac04f2.1b553e9968ac5a5835cad6f41704bb67.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", email: "Summer@gmail.com"}
])

Review.create!([
  {user_id: 4, teacher_id: 8, rating: 4, body: "What can be said about a person of academia with such vast knowledge in their craft. I was pleasantly humbled by my ignorance and will jump at the chance to work with this teacher again"},
  {user_id: 4, teacher_id: 9, rating: 2, body: "Fred was a gentle person but my learning style was incompatible with his. I wouldn't have bothered to write a review if he tried to meet me halfway but he didn't budge. I can understand being old school but gosh, it's 2022"},
  {user_id: 4, teacher_id: 11, rating: 5, body: "Summer is the absolute best. She listens when you have issues and does her utmost to correct and help you through them. Her guidance allowed me to break academic walls I was stuck at before."},
  {user_id: 4, teacher_id: 7, rating: 1, body: "Maybe I was just having a bad day but my experience was dreaful. You must adhere to strict rules and any slight hiccup is met with re-iteration without deeper explanation."},
  {user_id: 5, teacher_id: 11, rating: 2, body: "summer was nice but I found her lack of knowledge on certain questions I asked alarming. Mind you, My questions were niche but a teacher should have some of the answers."},
  {user_id: 5, teacher_id: 9, rating: 4, body: "The stern teaching style is somewhat of a dying art and I like the fact that Mr. McGuffin keeps the work structured and learning fairly optimal."},
  {user_id: 5, teacher_id: 7, rating: 4, body: "You'd think that younger teachers would be a problem but Ms. Teach was very knowledgeable and even if she didn't know something, she'd find out within a few minutes with some research. Very good teacher."},
  {user_id: 5, teacher_id: 8, rating: 3, body: "My experience with Ms. Peppermill was a normal teacher/student exchange. She assigned the work, I completed it and she explained the in betweens. It felt monotonous but effective."},
  {user_id: 6, teacher_id: 9, rating: 3, body: "Fred did well in explaining the content and helping me when I got stuck."},
  {user_id: 6, teacher_id: 7, rating: 3, body: "Ms. Teach proved the age old adage of listening to your elders (even though they aren't that much older) very true. I was able to grasp my work well enough."},
  {user_id: 6, teacher_id: 8, rating: 4, body: "I had a fun time with Ms. Peppermill. She made the content engaging while not straying from the before charted path."},
  {user_id: 6, teacher_id: 11, rating: 4, body: "Summer is great. Her bright personality combined with her knowledge and snappy response set her above the rest."}
])